FROM {{ src_registry }}/{{ item.value.image }}:{{ src_tag }}
MAINTAINER Neutron-devel
USER root

{% for repos in item.value.repos %}
  COPY {{ repos }} /tmp/{{ repos }}
  WORKDIR /tmp/{{ repos }}
{% endfor %}

RUN python setup.py install
USER {{ item.value.user }} 

