---

- hosts: "{{ deployment_hosts }}"
  tasks:
    - name: "Pull containers from registry"
      shell: |
        docker pull {{ registry }}/{{ item.value.image }}:{{ tag }}
      with_dict: "{{ containers }}"
      become: true

    - name: "Update running containers"
      shell: |
          IDS="$(sudo docker ps | grep {{ item.value.docker }} | awk '{ print $1 }')"
          for ID in $IDS; do
            sudo docker stop $ID
            sudo docker rm $ID
          done
      with_dict: "{{ containers }}"
      become: true

    - name: "Start the containers again with the new images"
      shell: |
        paunch --verbose apply \
               --file /var/lib/tripleo-config/hashed-docker-container-startup-config-step_4.json \
               --config-id tripleo_step4
      become: true

