---

- hosts: controllers 
  vars:
    containers_dict: "{{ lookup('dict', containers) }}"
  tasks:
    - name: "Pull containers from registry"
      shell: |
        docker pull {{ registry }}/{{ item.value.image }}:{{ tag }}
      loop: "{{ containers_dict }}"

    - name: "Update running containers"
      shell: |
          IDS="$(sudo docker ps | grep {{ item.value.docker }} | awk '{ print $1 }')"
          for ID in $IDS; do
            sudo docker stop $ID
            sudo docker rm $ID
          done
      loop: "{{ containers_dict }}"

    - name: "Start the containers again with the new images"
      shell: |
        paunch --verbose apply \
               --file /var/lib/tripleo-config/hashed-docker-container-startup-config-step_4.json \
               --config-id tripleo_step4

