---

- hosts: localhost
  tasks:
    - name: Creates directory
      file: path=/tmp/dockerbuild state=directory

    - name: "Synchronize sources to dockerbuild directory"
      synchronize:
        src: "../{{ item }}"
        dest: /tmp/dockerbuild/
      with_items: "{{ repos }}"

    - name: "Write Dockerfile"
      template:
        src: Dockerfile.j2
        dest: "/tmp/dockerbuild/Dockerfile.{{ item.key }}"
      with_dict: "{{ containers }}"

    - name: "Build docker container"
      shell: |
        cd /tmp/dockerbuild
        docker build \
               -f Dockerfile.{{ item.key }} \
               -t {{ registry }}/{{ item.value.image }}:{{ tag }} \
               . 2>&1 >build.{{ item.key }}.log
      with_dict: "{{ containers }}"

    - name: "Push containers to registry"
      shell: |
        docker push {{ registry }}/{{ item.value.image }}:{{ tag }}
        docker image rm {{ registry }}/{{ item.value.image }}:{{ tag }}
      with_dict: "{{ containers }}"

